# Generated by Django 3.2.9 on 2021-12-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10)),
                ('pid', models.IntegerField()),
                ('mid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('m1', models.FloatField()),
                ('m2', models.FloatField()),
                ('m3', models.FloatField()),
                ('avg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mid', models.BigAutoField(default=None, primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=20)),
                ('memailid', models.CharField(max_length=20)),
                ('mpassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.DateField()),
                ('r2', models.DateField()),
                ('r3', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('emailid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
