# Generated by Django 3.2.9 on 2021-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cse', '0002_auto_20211214_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='m1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='m2',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='m3',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
